### ISSUE TITLE
W3D5 T2: binder badge failed to render T2 notebook 

### ISSUE THREAD

**Issue by zuxfoucault** [NeuromatchAcademy/course-content#506] opened 2020-07-31 04:03 UTC

**Comment by mwaskom** [comment] 2020-07-31 11:30
We don’t provide binder badges. Do you mean  If so, this is a duplicate of #210. I don’t know that there’s anything we can do here, it may be a bug in nbviewer.

**Comment by zuxfoucault** [comment] 2020-08-01 02:18
yes, nbviewer. Since it's duplicate, I'll close this issue here.

**Closed** 2020-08-01 02:18 UTC
Labels: W3D5
